#!/usr/bin/env python3

import rospy
import tf

if __name__ == '__main__':
    print("Initializing...", end = '')
    rospy.init_node('robot_tf_publisher')
    rate = rospy.Rate(100)                  # 100 Hz
    br = tf.TransformBroadcaster()
    print("Done")
    while not rospy.is_shutdown():
        br.sendTransform((0.01,0.0,0.0),
                         (0,0,0,1),
                         rospy.Time.now(),
                         "base_virtual_laser",
                         "base_link")
        br.sendTransform((0.0,0.0,0.0),
                         tf.transformations.quaternion_from_euler(0, 0, 3.1415),
                         rospy.Time.now(),
                         "odom",
                         "map")
        rate.sleep()
