#! /usr/bin/env python3
import sys, rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge

import time

import anki_vector
from anki_vector import events
from anki_vector.util import degrees

if __name__ == "__main__":
    with anki_vector.Robot("00a10a53") as robot:
        #robot.behavior.set_head_angle(degrees(5))
        #input()
        #robot.behavior.set_head_angle(degrees(0))

        robot.motors.set_wheel_motors(20,20)
        time.sleep(8)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.motors.set_wheel_motors(0,10)
        time.sleep(4)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.motors.set_wheel_motors(20,20)
        time.sleep(4)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.motors.set_wheel_motors(10,0)
        time.sleep(8)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.motors.set_wheel_motors(20,20)
        time.sleep(8)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.motors.set_wheel_motors(10,0)
        time.sleep(8)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.motors.set_wheel_motors(20,20)
        time.sleep(4)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.motors.set_wheel_motors(0,10)
        time.sleep(4)
        robot.motors.set_wheel_motors(0,0)
        time.sleep(1)

        robot.behavior.turn_in_place(degrees(180))
        robot.behavior.drive_on_charger()
